import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={" bg-white m-0"}>{children}</body>

      {/* <body className={inter.className}>{children}</body> */}
    </html>
  );
}
